/**
 * @file Automatically generated by barrelsby.
 */

export * from './inventory-feature-search.module';
export * from './products-grid/products-grid.component';
export * from './products-search.component';
export * from './products-search.routes';
export * from './search-filters/search-filters.component';
