/**
 * @file Automatically generated by barrelsby.
 */

export * from './application/inventory.facade';
export * from './entities/product.dto';
export * from './entities/product.mapper';
export * from './entities/product.model';
export * from './infrastructure/inventory.service';
export * from './inventory-data.module';
