/**
 * @file Automatically generated by barrelsby.
 */

export * from './inventory-feature-product.module';
export * from './product.component';
export * from './product.routes';
export * from './product-actions/product-actions.component';
export * from './product-shipment/product-shipment.component';
